<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Vectorscript .. a Pascal variant based on the Chris Jacks Pascal bundle</string>
	<key>fileTypes</key>
	<array>
		<string>vss</string>
		<string>px</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(BEGIN|PROCEDURE|FUNCTION)</string>
	<key>foldingStopMarker</key>
	<string>^\s*END;</string>
	<key>name</key>
	<string>Vectorscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:(if|while|for|return))\b</string>
			<key>name</key>
			<string>keyword.control.vectorscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.vectorscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>comment.block.vectorscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(Abs|Absolute))\b</string>
			<key>name</key>
			<string>support.function.vectorscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.vectorscript</string>
	<key>uuid</key>
	<string>367C18F5-E673-4AB0-9E8F-054C1C71E3E4</string>
</dict>
</plist>
